version: '3.1'

services:
  deepintent-auction-app:
    build: .
    restart: always
    container_name: auction-app
    ports:
    - 8182:8080
    working_dir: /opt/app
    depends_on:
    - mongo

  mongo:
    image: mongo
    container_name: auction_app
    volumes:
    - $HOME/data/auction_app-data:/data/db
    - $HOME/data/auction_app-bkp:/data/bkp
    restart: always